language: node_js
node_js:
  - node
sudo: false
script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: jr21kOD19vE83VyPRbl4/eF6D8Ucv0h+Fzw5T3BKVBrw5TfE45zw8p9r9BGN84RtVlkrdqBYmzXEPQEjt/3Ri2jSvbw/1OONY4osZy0bTsTBhhy+80r6Hj41lCYXqCjVBbLUoXf/JjN7iCiyOXNl9f2kRPYQ+j6354qH0rtcSsjnMEs758jnRZy8xdXfyO9WDkzKC2eHQBtYB3GCw/0OnYv3hPlOIyxCEDWEXHytyxYUYI/K5UP+aLQIRJNTeKYBn7+A6+r/2lli7/CKT2/8Z6dzc7cqxp7RfJOznre/hvrsIZL1/2cVSMe/oFFSBqFwx3Dx+5hcbxMXju8YrLJwhWg83FmD3ok5xZVb4rAt6A60ny1xDsxF8Y/5OyLmA0n2e7zlEaTbKY+BwJD6JsL30u7hPD6ld3Qgeki60PzmzzX2Zkwg9/pbGOmWHPmSyA/T9vv4Wx2Kq+R5+Ylys4MJRiCIeBCszjzrnr6J6Nmdn35fmKmT6VRlwyhaeQAnPpahP/jPExE411xRSBhKQIJOFlijo487OZFE4hNM1c2PMhs6v+3RgYu/dgMa+2GA23cOmz/rc0TG1jLg5HVYg8E9zavMhOUcQn4/Mf71beOtocryuTm/HL/Fi1eHyU5Q1qte5GbN6yalI8mMJwXFeTLvch18gPwAVo/oF4JW3IBO91o=
  app: awax-app
  edge: true

