language: node_js
node_js:
  - node
sudo: false
script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: hPloW7w7/S+SOpYeMGKy3f5XvrGE2YTaHAE7xXQaCSxQk5MYG/AIUdfyiExyoN49kwuHdt/ByhBuzSQSCJ9J/gWa+Y6HeLnJWFbt1VLnQ3i5xRmEBnXmHHumH/7XUJQnvEQmr/igZpz6l5IrU/J77QtFHpXZFSQtHtU2s7lSiR57KbbYtfjJaCpO/p/Zi4Dl1g8mrR6gK1KWLR4OEJFhGBv8vlfMg6jczpAFiN9Xs14+SzYccOOVWdMQoxKz1PQsBjvt07tC+f+he2zQclwmO++SlXkXu1UOTu8zWVEi/qJKolsVDnrCzDGbhE/R/tLNGQznSKLuQRdQaydj7Ap9yr/JYoSnAfQoW6jhQ45BSIWgapTiX+FgDcJy1KStPFYs7HRsWa2vIPsrpDet9Bz/LtquTIpxSlkInpwrZel9fUb8qHRjXtDsHeSyxF5hIQzr3Ry6bQ1IxIKRK9Ji42/KVvp5dibNC/hhD+M7pjTWXQK/vhR+8659LTBVislc7bAwj878yjJ3kJwZHCRvyIe/TJSe1Fc8/jz6HOROA0SNxJvPOU7ZCE+eW8OiAAhCl5ZpVtt4aVtRCzYX+tJXL2pyot4qGddAwjxpr95Sd5MEaXcTuhySNKOHG8OG4VspytRPgtO6fEZU4DW7HLIdcYeqVwkpnNtR27vY0AQg+e0yzng=
  app: awax-app
  edge: true

